### ISSUE TITLE
Getting an Error when running this program.  Using Python 3.x.x

### ISSUE THREAD

**Issue by cmos10771** [t0x0/random#1]
C:\Users\cmoss\Desktop\WindowsIOT>python ffu2img.py Flash.FFU RPi.IMG
Input File: Flash.FFU
Output File: RPi.IMG
Error: security header signature incorrect.

Also, The pylint in VS 2013 Python tools, wants all the Print statements wrapped in parentheses.

**Comment by t0x0** [comment]
That error indicates a problem with the FFU image. What release are you using?

This is written for Python2, tested on 2.7.9. I'm sure there are a variety of items that are non-py3 compliant. I have no plans to fix them.

**Comment by cmos10771** [comment]
Okay, I just wanted to let you know.  Thanks.

**Comment by t0x0** [comment]
Have you tried with the current RPi release FFU? It's possible than Microsoft changed the signature between the current release (all I've tested with) and the version you have.

Can you pull the latest version of ffu2img and test again (with your current FFU)? You should now get additional output that details the signature that it is seeing. You can email me the log if you like, and I can look at that also.

**Comment by t0x0** [comment]
Upon further testing, the security header error will occur when running with python 3, if the other errors are ignored. this was likely the issue you experienced. you can try again with python 2, or there is now a python 3 version available.

**Comment by cmos10771** [comment]
Thank You.
