### ISSUE TITLE
Python 3.4.3 on Windows shows print error

### ISSUE THREAD

**Issue by migsantiago** [t0x0/random#2]
Hello

When I try to convert the Flash.FFU image in Windows with Python 3.4.3, the console (cmder) shows this error:

D:\raspberry_pi_2\win10_iot\Windows_IoT_Core_RPI2_BUILD
λ python ffu2img.py Flash.ffu RPi.IMG
  File "ffu2img.py", line 20
    print 'Input File: ' + ffupath
                       ^
SyntaxError: Missing parentheses in call to 'print'
![image](https://cloud.githubusercontent.com/assets/6674158/7671681/6c646696-fc9f-11e4-9f71-b68928f7210b.png)

I will try to run it on Linux.

Thanks.

**Comment by t0x0** [comment]
This is not written for Python 3. Please use Python 2.7.9.

**Comment by migsantiago** [comment]
OK, thanks!

**Comment by t0x0** [comment]
FYI, I have added a Python 3 version.

**Comment by migsantiago** [comment]
Good... make sure to pulbish it on the web. People will like the news. Thanks.
