### ISSUE TITLE
Python 2.7.9 Windows - SyntaxError: EOL while scanning string literal

### ISSUE THREAD

**Issue by migsantiago** [t0x0/random#3]
Hello, now using Python 2.7.9 for Windows this error is shown:

D:\raspberry_pi_2\win10_iot\Windows_IoT_Core_RPI2_BUILD
λ python ffu2img.py Flash.ffu Rpi.img
  File "ffu2img.py", line 35
    logfp.write('Exiting, incorrect signature: "' + signature '")
                                                                ^
SyntaxError: EOL while scanning string literal

D:\raspberry_pi_2\win10_iot\Windows_IoT_Core_RPI2_BUILD
λ python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

![image](https://cloud.githubusercontent.com/assets/6674158/7671788/597d96ee-fca2-11e4-85cd-3f60927026e5.png)

Thanks!

**Comment by t0x0** [comment]
Thanks, there was a missing closing quote. I've committed an update, please pull down the new version and try again. Sorry for the trouble.

**Comment by migsantiago** [comment]
No problem! It now shows this:

D:\raspberry_pi_2\win10_iot\Windows_IoT_Core_RPI2_BUILD
λ python ffu2img.py Flash.ffu Rpi.img
  File "ffu2img.py", line 35
    logfp.write('Exiting, incorrect signature: "' + signature '"')
                                                                ^
SyntaxError: invalid syntax

![image](https://cloud.githubusercontent.com/assets/6674158/7671834/9a5491c6-fca3-11e4-8e6f-1d03d39942d6.png)

**Comment by migsantiago** [comment]
Is it missing a '+' ?

**Comment by t0x0** [comment]
Yes, I haven't had my coffee yet. Updated.

**Comment by migsantiago** [comment]
Thank you. It generated an img file...

6417 blocks, 821376kb written - Delay expected. Please wait.
Write complete.

I will test it later.

**Comment by migsantiago** [comment]
It seems that Windows did boot. Thanks.

http://www.todopic.com.ar/foros/index.php?topic=44458.msg369480#msg369480

**Comment by t0x0** [comment]
Thanks for the link, good to see it worked.
